name: Java CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify the Java distribution (e.g., temurin)

    - name: Compile and Run Java Program
      run: |
        javac Addition.java
        java Addition
